# Order Approval Process
main:
  params: [args]
  steps:
    - checkAvailability:
        call: http.post
        args:
          url: https://check-availability-vyyo777p6q-uc.a.run.app
          body:
            route_id: ${args.route_id}
        result: GetAvailabilityResult
    - conditionalOnSeatAvailability:
        switch:
        - condition: ${GetAvailabilityResult.body.result <= 0}
          steps:
            - rejectOrder:
                return: ${"Sorry, there are no seats available and you can therefore not buy a ticket."}
        next: calcPrice
    - calcPrice:
        call: http.post
        args:
          url: https://calc-ticket-price-vyyo777p6q-uc.a.run.app
          body:
            route_id: ${args.route_id}
            time: ${args.time}
        result: GetPriceResult
        next: createTicket
    - createTicket:
        call: http.post
        args:
          url: http://35.223.193.139:5000/tickets
          headers:
            Authorization: ${"Bearer "+ args.auth_token}
          body:
            route_id: ${args.route_id}
            price: ${GetPriceResult.body.total}
        result: GetCreateTicketResult
        next: returnOutput
    - returnOutput:
        return: ${GetCreateTicketResult.body}