# Order Approval Process
main:
  params: [args]
  steps:
    - checkAvailability:
        call: http.post
        args:
          url: https://check-availability-vyyo777p6q-uc.a.run.app
          body:
            route_id: ${args.route_id}
            another_val: 123
        result: GetAvailabilityResult
    - conditionalOnSeatAvailability:
        switch:
        - condition: ${GetAvailabilityResult.body < 0}
          steps:
            - rejectOrder:
                return: ${"Sorry, there are no seats available and you can therefore not buy a ticket.}
        next: calcPrice
    - calcPrice:
        call: http.post
        args:
          url: https://calc-ticket-price-vyyo777p6q-uc.a.run.app
          body:
            route_id: ${args.route_id}
            distance: 10
            time: ${args.time}
        result: GetPriceResult
        next: createTicket
    - createTicket:
        call: http.post
        args:
          url: http://35.222.91.84:5000/tickets
          body:
            price: ${GetPriceResult.body}
            account_eamil: ${args.account_email}
        result: GetCreateTicketResult
        next: returnOutput
    - returnOutput:
        return: ${GetCreateTicketResult.body}